#!/bin/bash -e

for subcommand in \
    start stop kill clean \
    trace scan fake-compiler \
    add load config index \
    find-def grep complete \
; do
    clang-tags $subcommand --help >${subcommand}-help.out
done
