#!/bin/bash

set -e

TIME="/usr/bin/time --format %e --output tests.time"

echo -ne "scan     " 1>&2
${TIME} \
    clang-tags scan ../src -- -I. \
    >tests.tmp
echo $(cat tests.time) 1>&2


echo -ne "trace    " 1>&2
make clean
${TIME} \
    clang-tags trace make \
    >tests.tmp
echo $(cat tests.time) 1>&2


echo -ne "index    " 1>&2
${TIME} \
    clang-tags index \
    >tests.tmp 2>&1
if grep -q error tests.tmp; then false; else true; fi
echo $(cat tests.time) 1>&2


echo -ne "update   " 1>&2
${TIME} \
    clang-tags update \
    >tests.tmp 2>&1
if grep -q error tests.tmp; then false; else true; fi
echo $(cat tests.time) 1>&2


echo -ne "find-def " 1>&2
${TIME} \
    clang-tags find-def ../src/index.cxx 903 \
    >tests.tmp 2>&1
grep -q -F 'c:@N@Clang@C@SourceLocation@F@expansionLocation#1' tests.tmp
grep -q -F 'c:@N@Clang@C@Cursor@F@location#1' tests.tmp
grep -q -F 'c:index.cxx@557@F@indexFile#$@SA@CXCursor#S0_#*v#@cursor' tests.tmp
echo $(cat tests.time) 1>&2


echo -ne "grep     " 1>&2
${TIME} \
    clang-tags grep 'c:@N@Clang@C@Cursor@F@location#1' \
    >tests.tmp 2>&1
grep -q -F 'findDefinition.cxx:33:'  tests.tmp
grep -q -F 'findDefinition.cxx:52:'  tests.tmp
grep -q -F 'findDefinition.cxx:131:' tests.tmp
grep -q -F 'index.cxx:34:'           tests.tmp
grep -q -F 'clang/cursor.hxx:63:'    tests.tmp
echo $(cat tests.time) 1>&2
